# Generated by Django 2.2 on 2019-04-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CqEvent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmsg',
            old_name='timestamp',
            new_name='mid',
        ),
        migrations.RemoveField(
            model_name='eventmsg',
            name='date',
        ),
        migrations.AlterField(
            model_name='eventmsg',
            name='time',
            field=models.IntegerField(),
        ),
    ]
