# Generated by Django 2.2 on 2019-04-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CqEvent', '0002_auto_20190406_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmsg',
            name='message_raw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eventmsg',
            name='resource_remote',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='eventmsg',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
